### PR TITLE
Historical Passenger Road data for EUR/NEU from TRACCS data

### PR DESCRIPTION
**Pull request by Loisel**
... to avoid drastic changes, e.g., in NEU and EUR Bus shares from 2010 to 2020. Includes a refactoring of loadSources code to load TRACCS data.

Bus Share Before:
Screenshot_2022-06-27_14-02-30

After:
Screenshot_2022-06-27_14-01-24

### CODE REVIEW

**Comment by robertpietzcker** [comment]
any chance to have a compScen with old and new results? Then I could comment :-)
On the code itself, I am too far away from EDGE-T coding to be able to say anything

**Comment by Loisel** [comment]
Unfortunately I'm not able to run the new compScen. That's why I posted the numbers.

**Comment by robertpietzcker** [comment]
> hat's why I posted the numbers

sorry, I overlooked them. 

could you put them in one excel file and put them all to 0 trailing digits to make them comparable (before taking the snapshot)?

right now I have to click from image to image, forgetting all the values in between :-)

also, what are the two values at the bottom?

**Comment by Loisel** [comment]
Screenshot_2022-06-27_16-05-02
I do not have captions in my pdf, but I think this is the relevant plot. The numbers seem to match.

**Review by robertpietzcker — APPROVED** [review]
From the results this looks good (EUR) and ok (NEU) to me

**Pull request merged**
