### PR TITLE
Mix4 Trucks Adjustments

### PR DESCRIPTION
**Pull request by johannah-pik**
This PR features a fix for alternative Truck shares in Europe
image
Full CompScen here: https://cloud.pik-potsdam.de/index.php/apps/files/?dir=/Transport%20reloaded/Projects/Ariadne&fileid=15462741

### CODE REVIEW

**Review by jmuessel — APPROVED** [review]
The graphs look distorted but I think this is because of GitHub and would be different in a pdf / Rmd

**Comment by robertpietzcker** [comment]
In principle great - I am just wondering about the 25% stock share in 2030 in DEU - that seems quite high? 
in the ACEA projects, the sales shares only reach 25-60% in 2030 - it would need four years of ~50% sales shares to reach 25% of stock share.

**Comment by johannah-pik** [comment]
Update on the above matter:
Sales Large Trucks: 
image
Stock Large Trucks:
image

**Comment by johannah-pik** [comment]
Additionally, I included a small adjustment on small Trucks for CHA: 
Small Truck sales:
image
Small Truck Stock:
image
Small Truck Stock:
image
Large Truck Stock:
image
This affects also other regions
Full CompScens here: https://cloud.pik-potsdam.de/index.php/apps/files/?dir=/Transport%20reloaded/Transport_CompScens/230120%20Mix4%20Trucks%20Adjustemnts&fileid=15518411

**Comment by cchrisgong** [comment]
> Full CompScens here: https://cloud.pik-potsdam.de/index.php/apps/files/?dir=/Transport%20reloaded/Transport_CompScens/230120%20Mix4%20Trucks%20Adjustemnts&fileid=15518411

sorry I can't access the cs file... @johannah-pik

**Comment by johannah-pik** [comment]
> > Full CompScens here: https://cloud.pik-potsdam.de/index.php/apps/files/?dir=/Transport%20reloaded/Transport_CompScens/230120%20Mix4%20Trucks%20Adjustemnts&fileid=15518411
> 
> sorry I can't access the cs file... @johannah-pik

Sorry - here is another Link: https://cloud.pik-potsdam.de/index.php/s/Lo4ZTkg8yn5QHDz
PW:XnT9ccco

**Comment by cchrisgong** [comment]
Thanks! It all looks good to me :)

**Comment by cchrisgong** [comment]
Thanks! It all looks good to me :)

**Pull request merged**
