### PR TITLE
Bugfix incotrend

### PR DESCRIPTION
**Pull request by johannah-pik**
A bug in the incotrend function led to scenario-specific differences in the historical final energy demand. The problem occured because the scenario-specific mitigation factors were applied from 2020 onwards. This has been changed now to 2025

### CODE REVIEW

**Comment by Loisel** [comment]
Yeah, well, actually this *has* been 2025 before and was changed to 2020 due to a request by @robertpietzcker

**Comment by johannah-pik** [comment]
@robertpietzcker this will certainly be the case when I merge the PR. Unless Alois changed the underlying sw trends in 2020. I will put this issue on the to do in our google doc. The question is now whether to merge or not to merge? :P

**Comment by robertpietzcker** [comment]
> @robertpietzcker this will certainly be the case when I merge the PR. Unless Alois changed the underlying sw trends in 2020. I will put this issue on the to do in our google doc. The question is now whether to merge or not to merge? :P

I am not sure how to interpret "this will certainly be the case". 

I guess you have the before/after runs at hand - maybe it would be best to show the changes of 2020 values (values or compScen plot) in an issue linked here?

**Comment by johannah-pik** [comment]
Here are the LDV sales for Large Car and SUV before:
Stock:
image
Sales
image


And after:
Stock:
image
Sales: 
image
Legend: 
image
Full CompScens for EUR & H12 can be found here: https://cloud.pik-potsdam.de/index.php/apps/files/?dir=/Transport%20reloaded/Transport_CompScens/221109%20Mix1-4%20before%20and%20after%20bugfix%20incotrend&fileid=14750202

**Comment by johannah-pik** [comment]
I am not sure what you had in mind, when you decided to start with the mitigation scenarios in 2020 already. But it does not affect the share of BEVs in the LDV sales. This is reasonable, because the logistic mitigation trends are only applied on the shareweights and do not affect the LDV inconvenience costs. So we can see here only the shift to public and active modes that sets in earlier (before the fix presented in this PR)

**Comment by johannah-pik** [comment]
@robertpietzcker here are the CompScens with direkt comparison of Mix2 and Mix4 before/after https://cloud.pik-potsdam.de/index.php/apps/files/?dir=/Transport%20reloaded/Transport_CompScens/221109%20Mix1-4%20before%20and%20after%20bugfix%20incotrend/Mix2and4_directComparison&fileid=14809684

**Comment by robertpietzcker** [comment]
> @robertpietzcker here are the CompScens with direkt comparison of Mix2 and Mix4 before/after

Looks good - Thanks for providing this comparison!

**Review by robertpietzcker — APPROVED** [review]
I can't comment on the R implementation, but output-wise it looks good!

**Pull request merged**
