### PR TITLE
Add configuration tables for the demand regression

### PR DESCRIPTION
**Pull request by Loisel**
Tables to modify the demand regression can be passed to `lvl2_demandReg` (arguments `ssp_factors` and `regional_factors`).  There are two configuration layers. On top of the income based elasticity trends we apply first a SSP/SDP factor and then a regional and SSP/SDP specific factor. The missing years are interpolated linearly.
The factors are applied by addition: `elasticity = baseline_elasticity + ssp_factor + regional_factor`

Usage:
For `generateEDGEdata`, specify the parameters `ssp_demreg.path` and `regional_demreg.path` to point to CSV files with the correct format. The format is as follows:
- `ssp_demreg.path` has dimensions **SSP_scenario**, **var** (to specify pass/freight short/long) and years **2020, 2030, 2050, 2100**.
- `regional_demreg.path` has dimensions **SSP_scenario**, **region**, **var** (to specify pass/freight short/long) and years **2020, 2030, 2050, 2100**.

**Note:** All entries that are not specified default to 0.

### CODE REVIEW

**Comment by Loisel** [comment]
Example:
```
SSP_scenario,var,2020,2030,2050,2100
SDP_RC,income_elasticity_pass_lo,0,-0.02,-0.05,-0.1
SDP_RC,income_elasticity_pass_sm,0,-0.05,-0.1,-0.1
```

**Comment by MariannaR** [comment]
Thanks for the addition! Is the table with the starting values supposed to be shipped with the package as well?

**Comment by Loisel** [comment]
Well, we do this for the other config files as well, so I'd say yes, we ship in in `inst/extdata`.

**Comment by MariannaR** [comment]
I see, will the table be included in another PR? I do not seem to be able to find it here

**Comment by Loisel** [comment]
> I see, will the table be included in another PR? I do not seem to be able to find it here

There is no table yet. Note also that the way this is set up, you supply only values that you want to change. All other entries are left untouched. If there are no tables supplied, all entries are left untouched. In this regard this configuration file is used differently than the others.

**Review by MariannaR — APPROVED** [review]

**Comment by MariannaR** [comment]
Thanks for the explanation!

**Review by johannah-pik — APPROVED** [review]

**Pull request merged**
