### PR TITLE
Avoid writing to the package repository in compare scenario

### PR DESCRIPTION
**Pull request by mikapfl**
compareScenarios_EDGET used to call render() directly on the files in the package repository. Unfortunately, render() will call pdflatex such that it tries to write its log file in the directory containing the file to be rendered. That will then fail if you don't have the rights to write in the package repo - or if someone else is also render()ing at the same time.

With this PR, the template directory will instead be copied to the output directory and render() will be called on that, ensuring that we have exclusive access and the necessary rights. The templates are removed afterwards to not blow up the output directory unnecessarily.

### CODE REVIEW

**Comment by mikapfl** [comment]
@pweigmann Do we need a similar fix also for regular compareScenarios? Do you know whom I could ask?

**Comment by pweigmann** [comment]
> @pweigmann Do we need a similar fix also for regular compareScenarios? Do you know whom I could ask?

Given the render statement looks similar for [cs2](https://github.com/pik-piam/remind2/blob/0a9a6e5be10996e0d4d4652fffc1bc8cd3ac53f0/R/compareScenarios2.R#L153) I am inclined to say we need it.

**Comment by mikapfl** [comment]
> similar
ah, a case of good-old copy'n'paste. Yeah, I'll prepare a pull request for remind2 as well.

**Review by johannah-pik — APPROVED** [review]
Thanks, Mika, for fixing this :)
Our transport CompScen is a child of the early CompScen2 - so if it hasn't been fixed in the meantime, the problem occurs there too.

**Comment by mikapfl** [comment]
@pweigmann I didn't find the time to fix this in the original CompScen2, maybe you can do that? Should be a rather obscure error, but very hard to debug if it happens.

**Pull request merged**
