### PR TITLE
Update regional_regression_factors.csv

### PR DESCRIPTION
**Pull request by johannah-pik**
Changes applied by Robert 12/05/2022

### CODE REVIEW

**Review by robertpietzcker — APPROVED** [review]

**Comment by Loisel** [comment]
Wow that is a lot of changes. Some comments would be helpful @robertpietzcker 
plus, you might want to apply these adjustments also to the other scenarios.

**Comment by robertpietzcker** [comment]
I updated the elasticities with the following objectives: 
+ reduce CHA freight demand increase in the short term to better match IEA FE trajectories
+ reduce OAS demand in the short term to better match IEA FE trajectories
+ reduce the amount of crossing of per-capita ES demands over GDP/cap of different regions (if there didn't seem to be an explicit reason why there should be a crossing)
+ keep the trajectories smooth

**Comment by johannah-pik** [comment]
The changes were now also applied to SSP1, SSP5 and SSP2EU

**Comment by Loisel** [comment]
Bitte auch idealerweise die Reihenfolge der Szenarien einhalten, dann sieht man direkt was sich geändert hat

**Pull request merged**
